// SmileCRM city landing page dataset — 60 Indian cities
export const cities = [
  { slug: "mumbai", name: "Mumbai", state: "Maharashtra", tier: 1, region: "western" },
  { slug: "delhi", name: "Delhi", state: "Delhi", tier: 1, region: "northern" },
  { slug: "bangalore", name: "Bangalore", state: "Karnataka", tier: 1, region: "southern" },
  { slug: "hyderabad", name: "Hyderabad", state: "Telangana", tier: 1, region: "southern" },
  { slug: "chennai", name: "Chennai", state: "Tamil Nadu", tier: 1, region: "southern" },
  { slug: "pune", name: "Pune", state: "Maharashtra", tier: 1, region: "western" },
  { slug: "kolkata", name: "Kolkata", state: "West Bengal", tier: 1, region: "eastern" },
  { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", tier: 1, region: "western" },
  { slug: "jaipur", name: "Jaipur", state: "Rajasthan", tier: 2, region: "northern" },
  { slug: "surat", name: "Surat", state: "Gujarat", tier: 2, region: "western" },
  { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "nagpur", name: "Nagpur", state: "Maharashtra", tier: 2, region: "central" },
  { slug: "indore", name: "Indore", state: "Madhya Pradesh", tier: 2, region: "central" },
  { slug: "thane", name: "Thane", state: "Maharashtra", tier: 2, region: "western" },
  { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh", tier: 2, region: "central" },
  { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", tier: 2, region: "southern" },
  { slug: "patna", name: "Patna", state: "Bihar", tier: 2, region: "eastern" },
  { slug: "vadodara", name: "Vadodara", state: "Gujarat", tier: 2, region: "western" },
  { slug: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "ludhiana", name: "Ludhiana", state: "Punjab", tier: 2, region: "northern" },
  { slug: "agra", name: "Agra", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "nashik", name: "Nashik", state: "Maharashtra", tier: 2, region: "western" },
  { slug: "faridabad", name: "Faridabad", state: "Haryana", tier: 2, region: "northern" },
  { slug: "meerut", name: "Meerut", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "rajkot", name: "Rajkot", state: "Gujarat", tier: 2, region: "western" },
  { slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra", tier: 2, region: "western" },
  { slug: "amritsar", name: "Amritsar", state: "Punjab", tier: 2, region: "northern" },
  { slug: "navi-mumbai", name: "Navi Mumbai", state: "Maharashtra", tier: 2, region: "western" },
  { slug: "prayagraj", name: "Prayagraj", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "ranchi", name: "Ranchi", state: "Jharkhand", tier: 2, region: "eastern" },
  { slug: "howrah", name: "Howrah", state: "West Bengal", tier: 2, region: "eastern" },
  { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", tier: 2, region: "southern" },
  { slug: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh", tier: 2, region: "central" },
  { slug: "gwalior", name: "Gwalior", state: "Madhya Pradesh", tier: 2, region: "central" },
  { slug: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh", tier: 2, region: "southern" },
  { slug: "jodhpur", name: "Jodhpur", state: "Rajasthan", tier: 2, region: "northern" },
  { slug: "madurai", name: "Madurai", state: "Tamil Nadu", tier: 2, region: "southern" },
  { slug: "raipur", name: "Raipur", state: "Chhattisgarh", tier: 2, region: "central" },
  { slug: "kota", name: "Kota", state: "Rajasthan", tier: 2, region: "northern" },
  { slug: "chandigarh", name: "Chandigarh", state: "Chandigarh", tier: 2, region: "northern" },
  { slug: "guwahati", name: "Guwahati", state: "Assam", tier: 2, region: "northeastern" },
  { slug: "solapur", name: "Solapur", state: "Maharashtra", tier: 3, region: "western" },
  { slug: "hubballi", name: "Hubballi", state: "Karnataka", tier: 3, region: "southern" },
  { slug: "tiruchirappalli", name: "Tiruchirappalli", state: "Tamil Nadu", tier: 3, region: "southern" },
  { slug: "bareilly", name: "Bareilly", state: "Uttar Pradesh", tier: 3, region: "northern" },
  { slug: "moradabad", name: "Moradabad", state: "Uttar Pradesh", tier: 3, region: "northern" },
  { slug: "mysuru", name: "Mysuru", state: "Karnataka", tier: 3, region: "southern" },
  { slug: "gurugram", name: "Gurugram", state: "Haryana", tier: 2, region: "northern" },
  { slug: "noida", name: "Noida", state: "Uttar Pradesh", tier: 2, region: "northern" },
  { slug: "dehradun", name: "Dehradun", state: "Uttarakhand", tier: 3, region: "northern" },
  { slug: "jalandhar", name: "Jalandhar", state: "Punjab", tier: 3, region: "northern" },
  { slug: "mangaluru", name: "Mangaluru", state: "Karnataka", tier: 3, region: "southern" },
  { slug: "kochi", name: "Kochi", state: "Kerala", tier: 2, region: "southern" },
  { slug: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala", tier: 2, region: "southern" },
  { slug: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", tier: 2, region: "eastern" },
  { slug: "salem", name: "Salem", state: "Tamil Nadu", tier: 3, region: "southern" },
  { slug: "warangal", name: "Warangal", state: "Telangana", tier: 3, region: "southern" },
  { slug: "guntur", name: "Guntur", state: "Andhra Pradesh", tier: 3, region: "southern" },
];

export function getCityBySlug(slug) {
  return cities.find((c) => c.slug === slug) || null;
}

export function getAllCitySlugs() {
  return cities.map((c) => c.slug);
}
