-- ============================================================
-- Clinic Digital Score — Supabase Setup
-- Run this in Supabase SQL Editor (supabase.com → SQL Editor)
-- ============================================================

-- 1. Create table
CREATE TABLE IF NOT EXISTS clinic_score_submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  doctor_name TEXT,
  clinic_name TEXT,
  city TEXT NOT NULL,
  score INTEGER NOT NULL CHECK (score >= 0 AND score <= 100),
  tier TEXT NOT NULL,
  answers JSONB NOT NULL,
  email TEXT,
  phone TEXT,
  lead_created BOOLEAN DEFAULT false
);

-- 2. Index for fast percentile queries
CREATE INDEX IF NOT EXISTS idx_clinic_score_city ON clinic_score_submissions(city);
CREATE INDEX IF NOT EXISTS idx_clinic_score_city_score ON clinic_score_submissions(city, score);

-- 3. Row Level Security — allow public inserts, block reads
ALTER TABLE clinic_score_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts" ON clinic_score_submissions
  FOR INSERT TO anon WITH CHECK (true);

-- Reads are blocked by default (no SELECT policy for anon)

-- 4. Percentile function (used by the page to rank the user)
CREATE OR REPLACE FUNCTION get_clinic_score_percentile(p_city TEXT, p_score INTEGER)
RETURNS NUMERIC AS $$
  SELECT ROUND(
    COUNT(*) FILTER (WHERE score < p_score) * 100.0 / NULLIF(COUNT(*), 0)
  )
  FROM clinic_score_submissions
  WHERE city = p_city;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

-- Grant execute to anon role
GRANT EXECUTE ON FUNCTION get_clinic_score_percentile(TEXT, INTEGER) TO anon;

-- 5. Seed 200 synthetic submissions across top Indian cities
-- Scores distributed realistically: median ~42, tail at 0-30 and 76-100
INSERT INTO clinic_score_submissions (city, score, tier, answers) VALUES
-- Mumbai (40 rows)
('Mumbai', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Mumbai', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Mumbai', 30, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 62, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Mumbai', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 78, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Mumbai', 25, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 67, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Mumbai', 10, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 90, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Mumbai', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Mumbai', 58, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 74, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"WhatsApp or phone call","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Mumbai', 20, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 50, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Mumbai', 82, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Mumbai', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 44, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"Walk-in only","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 69, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Mumbai', 5, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 32, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 76, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Mumbai', 53, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 40, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 63, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 28, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 87, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Mumbai', 47, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Mumbai', 60, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 56, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Mumbai', 80, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Mumbai', 12, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 37, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Mumbai', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
-- Delhi (30 rows)
('Delhi', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 70, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Delhi', 20, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Delhi', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Delhi', 62, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Delhi', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Delhi', 78, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Delhi', 30, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 67, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Delhi', 8, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Delhi', 90, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Delhi', 25, 'Digital Newcomer', '{"gbp":"No","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Delhi', 73, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"WhatsApp or phone call","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Delhi', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 58, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 80, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Delhi', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Delhi', 12, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 50, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Delhi', 75, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Delhi', 32, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Delhi', 60, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 22, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Delhi', 88, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
-- Bengaluru (25 rows)
('Bengaluru', 40, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 76, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Bengaluru', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 58, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Bengaluru', 82, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Bengaluru', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Bengaluru', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Bengaluru', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"WhatsApp or phone call","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Bengaluru', 28, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Bengaluru', 90, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Bengaluru', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Bengaluru', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Bengaluru', 10, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 50, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Bengaluru', 79, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Bengaluru', 32, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 62, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Bengaluru', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 73, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Bengaluru', 25, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bengaluru', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
-- Pune (20 rows)
('Pune', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Pune', 20, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 82, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Pune', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Pune', 60, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Pune', 77, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Pune', 28, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 70, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Pune', 10, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 88, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Pune', 33, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Pune', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Pune', 75, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
-- Chennai, Hyderabad, Jaipur, Ahmedabad, Other (combined 85 rows)
('Chennai', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Chennai', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Chennai', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Chennai', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Chennai', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Chennai', 60, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Chennai', 25, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Chennai', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Chennai', 78, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Chennai', 32, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Hyderabad', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Hyderabad', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Hyderabad', 12, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Hyderabad', 80, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Hyderabad', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Hyderabad', 63, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"No reminders sent","followup":"Never"}'),
('Hyderabad', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Hyderabad', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Hyderabad', 87, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Hyderabad', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Jaipur', 30, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Jaipur', 62, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Jaipur', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Jaipur', 75, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Jaipur', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Jaipur', 82, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Jaipur', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Ahmedabad', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Ahmedabad', 70, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Ahmedabad', 28, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Ahmedabad', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Ahmedabad', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Ahmedabad', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Ahmedabad', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Kolkata', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Kolkata', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Kolkata', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Kolkata', 78, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Kolkata', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Noida', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Noida', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Noida', 18, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Noida', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Noida', 40, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Lucknow', 30, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Lucknow', 58, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Lucknow', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Lucknow', 75, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Surat', 25, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Surat', 62, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Surat', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Surat', 80, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Chandigarh', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Chandigarh', 70, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Chandigarh', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Chandigarh', 85, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Kochi', 38, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Kochi', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Kochi', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Kochi', 78, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Sometimes, manually"}'),
('Indore', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Indore', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Indore', 20, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Bhopal', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Bhopal', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Bhopal', 55, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Nagpur', 48, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Nagpur', 75, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Nagpur', 28, 'Digital Newcomer', '{"gbp":"Yes, unsure if verified","reviews":"1–10 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Visakhapatnam', 40, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Never"}'),
('Visakhapatnam', 65, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Patna', 22, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Patna', 52, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Other', 45, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"Manual reminder calls","followup":"Never"}'),
('Other', 68, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Sometimes, manually"}'),
('Other', 20, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Other', 80, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}'),
('Other', 35, 'Getting Started', '{"gbp":"Yes, unsure if verified","reviews":"11–49 reviews","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Other', 58, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"11–49 reviews","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Manual reminder calls","followup":"Never"}'),
('Other', 15, 'Digital Newcomer', '{"gbp":"No","reviews":"None","review_response":"Rarely or never","booking":"Walk-in only","reminders":"No reminders sent","followup":"Never"}'),
('Other', 72, 'Digital-Forward', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Sometimes","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Never"}'),
('Other', 42, 'Getting Started', '{"gbp":"Yes, verified ✓","reviews":"1–10 reviews","review_response":"Sometimes","booking":"WhatsApp or phone call","reminders":"No reminders sent","followup":"Sometimes, manually"}'),
('Other', 88, 'AI-Ready Clinic', '{"gbp":"Yes, verified ✓","reviews":"50 or more","review_response":"Yes, within 24 hours","booking":"Online booking (website or app)","reminders":"Yes — WhatsApp or SMS auto-reminders","followup":"Yes — automated follow-up messages"}');
-- Total: 200 rows across Mumbai(40), Delhi(30), Bengaluru(25), Pune(20), Chennai(10),
--        Hyderabad(10), Jaipur(7), Ahmedabad(7), Kolkata(5), Noida(5), Lucknow(4),
--        Surat(4), Chandigarh(4), Kochi(4), Indore(3), Bhopal(3), Nagpur(3),
--        Visakhapatnam(2), Patna(2), Other(10)

-- Verify
SELECT COUNT(*) AS total_rows FROM clinic_score_submissions;
SELECT city, COUNT(*) FROM clinic_score_submissions GROUP BY city ORDER BY COUNT(*) DESC;
